# SQLite version 3.x
#   gem install sqlite3-ruby
test: &test
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

foo:
  <<: *test
  database: db/test-foo.sqlite3

bar:
  <<: *test
  database: db/test-bar.sqlite3
