test: &test
  adapter: postgresql
  database: brick_test
  username: postgres
  password: 
  host:     localhost
  port:     5432

foo:
  <<: *test
  database: brick_foo

bar:
  <<: *test
  database: brick_bar
