# frozen_string_literal: true

class Fluxor < ActiveRecord::Base
  # Generated by:  Fluxor.suggest_template(true, true, 1, true)
  IMPORT_TEMPLATE = {
    uniques: [:name, :widget_name, :widget_wotsit_name, :widget_foo_habtms_name, :widget_foo_hmts_name],
    required: [],
    all: [:name,
      { widget: [:name, :a_text, :an_integer, :a_float, :a_decimal, :a_datetime, :a_time, :a_date, :a_boolean, :type,
        { wotsit: [:name] },
        { foo_habtms: [:name] },
        { foo_hmts: [:name] }] }],
    as: {}
  }.freeze

  if ActiveRecord.version >= Gem::Version.new('5.0')
    belongs_to :widget, optional: true
  else
    belongs_to :widget
  end
end
