# frozen_string_literal: true

class Wotsit < ActiveRecord::Base
  # Generated by:  Wotsit.suggest_template(true, true, 1, true)
  IMPORT_TEMPLATE = {
    uniques: [:name, :widget_name, :widget_fluxors_name],
    required: [],
    all: [:name,
      { widget: [:name, :a_text, :an_integer, :a_float, :a_decimal, :a_datetime, :a_time, :a_date, :a_boolean, :type,
        { fluxors: [:name] }] }],
    as: {}
  }.freeze

  if ActiveRecord.version >= Gem::Version.new('5.0')
    belongs_to :widget, optional: true
  else
    belongs_to :widget
  end

  def created_on
    created_at.to_date
  end
end
