# frozen_string_literal: true

module Brick
  class AirtableApiCaller
    class << self
      include FancyGets

      def pick_tables(usage = :migrations)
        puts "In order to reference Airtable data you will need a Personal Access Token (PAT) which can be generated by referencing this URL:
  https://airtable.com/create/tokens
You need only #{usage == :migrations ? 'this scope:' : "these three scopes:
  data.records:read
  data.recordComments:read"}
  schema.bases:read

Please provide your Airtable PAT:"
        pat = gets_password
        require 'net/http'
        # Generate a list of bases that can be chosen
        bases = https_get('https://api.airtable.com/v0/meta/bases', pat)
        base = gets_list(bases.fetch('bases', nil)&.map { |z| AirtableObject.new(z['id'], z['name']) })
        puts
        # Generate a list of tables that can be chosen
        objects = https_get("https://api.airtable.com/v0/meta/bases/#{base.id}/tables", pat).fetch('tables', nil)
        if objects.blank?
          puts "No tables found in base #{base.name}."
          return
        end

        tables = objects.map { |z| AirtableObject.new(z['id'], z['name'], z['primaryFieldId'], z['fields'], z['views']) }
        chosen = gets_list(tables, tables.dup)
        puts
        chosen
      end

    private

      def https_get(uri, bearer)
        uri = URI(uri) unless uri.is_a?(URI)
        https = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Get.new("#{uri.path}?#{uri.query}")
        request['Authorization'] = "Bearer #{bearer}"
        response = Net::HTTP.start(uri.hostname, uri.port, { use_ssl: true }) do |http|
          http.request(request)
        end
        # if response.code&.to_i > 299
        # end
        JSON.parse(response.body)
      end

      class AirtableObject
        attr_accessor :id, :name, :primary_key, :fields, :views
        def initialize(id, name,
                      primary_key = nil, fields = nil, views = nil)
          self.id = id
          self.name = name
          self.primary_key = primary_key
          self.fields = fields
          self.views = views
        end

        def to_s
          name
        end
      end
    end
  end
end
